### ISSUE TITLE
Unable to configure Speedtest

### ISSUE THREAD

**Issue by raj24365** [miquels/speedtest#10]
Hi Team,

Thank you for the great script to test the internet speed, I'm running into issues when I try to replicate the process outlined there.  I have installed all the requirements (nodejs, yarn, go compiler) for this algorithm to run however I'm not able to install it, can anyone advise me, please?
I'm not able to run the below steps, please see error screenshot 

# install configuration file
cp static/config.json.example static/config.json
vim static/config.json

# serve with hot reload at localhost:8080
yarn serve

# build for production with minification
yarn build
![speed test error](https://user-images.githubusercontent.com/66267509/83431687-5d236e80-a455-11ea-8658-29320d349aa0.JPG)

**Comment by miquels** [comment]
Oh that's just a typo in the README. I [fixed it](https://github.com/miquels/speedtest/commit/b1b5b345e4f6987eacae81d9a78a33b8617e773e).
