### ISSUE TITLE
TLS is required for a real public facing service

### ISSUE THREAD

**Issue by elico** [miquels/speedtest#12]
I have tested this service and these days with TLS everywhere you must run the service with TLS.
The basic static files can be served under any generic web service ie: apache\nginx etc.
However the api/speedtest service run's by default in plain HTTP which browsers do not allow.
(A mix of secure and non-secure urls)

To resolve this issue what I am doing adding the:
`Upgrade-Insecure-Requests: 1` header and the browsers automatically tries to upgrade the websocket and api connections with TLS.

What left to do on the speedtest api service is to add a TLS port and add the header into the default port.

**Comment by miquels** [comment]
You can now configure `https` as protocol in `config.json`. I've rewritten the backend server in Rust and while I was at it added TLS support to the backend server, so you don't need to route the actual downloads/uploads through your frontproxy.

**Comment by elico** [comment]
@miquels Thanks.
