### ISSUE TITLE
X-Forwarded-For support

### ISSUE THREAD

**Issue by elico** [miquels/speedtest#15]
Would it be possible to add X-Forwarded-For or another header name that will reflect the real client IP when the service is being a WAF?

**Comment by miquels** [comment]
Something like this? https://github.com/miquels/speedtest/commit/4a8ffe9f5763ae28e7e1c8fc6df9bb65147d6ac5

**Comment by elico** [comment]
@miquels I think this is it. (Since I am new to Rust)

**Comment by miquels** [comment]
yes it's not really documented, but it will use the XFF headers if the request comes from localhost, or if you pass the `--xff-headers` command line option to the server.
