### ISSUE TITLE
make: *** [get] Error 127

### ISSUE THREAD

**Issue by thiagoe** [miquels/speedtest#2]
Hi want try you project, i think him is great.

But when i ll run comand # yarn run build-server 
receive this error msg: 

yarn run v0.21.3
$ make -C server 
make: Entering directory '/var/www/html/sp/server'
server: getting dependencies..
go get
make: go: Comando não encontrado
Makefile:14: recipe for target 'get' failed
make: *** [get] Error 127
make: Leaving directory '/var/www/html/sp/server'
error Command failed with exit code 2.

Any idea about this problem?

My system debian jessie,  build-essential ok,

**Comment by miquels** [comment]
Hello. Seems like you do not have 'go' installed. Do
```
apt-get install golang-go
```
and try again.

**Comment by thiagoe** [comment]
So, i installed golang-go and error change, i need do any adsjustment, need change evionment to dir application
export GOPATH=/var/www/html/sp/
export GOBIN=/var/www/html/sp/

**Comment by thiagoe** [comment]
So, i installed golang-go and error change, is need adjustments, change evionment to dir application
#export GOPATH=/var/www/html/sp/
#export GOBIN=/var/www/html/sp/

In repository debian go lang is version 1.3, for get websocket i need update to version 1.6. ( i think version 1.7 work too) After this 2 things #yarn run build-server run ok and # server/server too run ok .

Now i see server runing # ps -aux |grep server but when i ll point web browser to index.html dont open, only blank page.

**Comment by miquels** [comment]
Hmm, it could be anything, but if you're using Safari it's missing 'fetch' support. I added a fetch polyfill in https://github.com/miquels/speedtest/commit/090b87ebad441882d262e85a67253d6da18a05b1 . I've also updated the README file with a bit more detail.
