### ISSUE TITLE
Missing wsip in server-go

### ISSUE THREAD

**Issue by MarcHagen** [miquels/speedtest#21]
Maybe this was forgotten, or you didn't want to implement this.
But the /speedtest/wsip endpoint doens't exists in the server-go. Which gives me errors in the client console.

Im not able to run the Rust server, so that doens't fix it either

**Comment by elico** [comment]
@MarcHagen on What OS? CPU? .. You are not able to run the Rust server?

**Comment by MarcHagen** [comment]
A good friend hosts the server. I have access with SSH in a chrooted environment.
Go is already installed, so building that was no issue.

But Rust won't install 
```
$ Linux <snip> 5.4.65-1-pve #1 SMP PVE 5.4.65-1 (Mon, 21 Sep 2020 15:40:22 +0200) x86_64 x86_64 x86_64 GNU/Linux
$ CentOS Linux release 8.2.2004 (Core)
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup: need 'uname' (command not found)
```

he says he doens't want to install rust on the server itself. :( 

If you could provide a binary i can run thats fine to i suppose :)

**Comment by elico** [comment]
I posted a docker container that does that already.
I will look at it later today.

**Comment by miquels** [comment]
The go server is not maintained anymore. I could delete it, but I think I will move it to "Attic" or somesuch, in case someone wants to resurrect it.
