### ISSUE TITLE
Would it be possible to add compatablity to https://github.com/showwin/speedtest-go

### ISSUE THREAD

**Issue by elico** [miquels/speedtest#24]
The tool: https://github.com/showwin/speedtest-go is a cli speedtest software.
Their download and upload speed algorightms are at:
https://github.com/showwin/speedtest-go/blob/master/speedtest/request.go#L19-L137

Would it be possible to add compatibility to their tool in the server side?

Thanks,

**Comment by miquels** [comment]
Closing this issue because I'm archiving this repository.
