### ISSUE TITLE
bargraph don't work

### ISSUE THREAD

**Issue by enryIT** [miquels/speedtest#3]
Hello,

I'm testing this app in order to excersize with Vue.js.
I've a problem with the bar graphs, they simply remain blank while the test runs fine and complete. I've checked the code and I can't seem to find the culrpit here.

Thanks

**Comment by miquels** [comment]
Let me guess- using Safari? I've only really tested it with Chrome and Firefox.

**Comment by enryIT** [comment]
Chrome and Firefox, both don't work.
Also tried Vivaldi, Opera and Edge, the up and down graphs aren't drawed at
all, they simply stay blank.

Il mer 15 mar 2017, 14:38 Miquel van Smoorenburg <notifications@github.com>
ha scritto:
