### ISSUE TITLE
No timeout or any fencing mechanism on the http server

### ISSUE THREAD

**Issue by elico** [miquels/speedtest#4]
I installed the service on a pretty heavy hardware and I noticed that for some reason there are spikes of 100% CPU load on one core from one of the http service procceses.
I reviewed the service and found out that someone with enough bandwidth can hammer the server without any limit.
I added a feature that fences the service from staying in the for loops for more then a specific ammount of seconds(cli flag\variable).
I also believe that in a public facing speed testing service logging should be turned off by default and should be turned on only for debugging since the service can be flooded with lots of connections.

**Comment by NikasZalias** [comment]
@elico how did you fixed the problem?

**Comment by NikasZalias** [comment]
@miquels

**Comment by elico** [comment]
@NikasZalias Sorry for the long pause.
I am not sure yet what I did back then.
From what I remember, back then I was looking at a basic Golang HTTP server session timeout.
I hope that in couple weeks I will be able to try and understand this issue with hope to find the relevant lines of code somewhere.

**Comment by miquels** [comment]
Well I just rewrote the backend server in Rust...

**Comment by elico** [comment]
@miquels any hints on how it can be compiled on Debian or CentOS?

**Comment by miquels** [comment]
It's in the main README. Install Rust using rustup, then run `cargo build --release` in the `server/` directory.

**Comment by elico** [comment]
@NikasZalias The GoLang timeout was based on:
* https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/
or
* https://github.com/snail007/goproxy/blob/master/utils/io-limiter.go

I don't remember which one of them :\

**Comment by miquels** [comment]
I've added a 20 second timeout for /api/send and /api/sink in the new server code, see https://github.com/miquels/speedtest/commit/96d01ad134afcbeefc3808a6dd77f29c71798629 .

**Comment by elico** [comment]
@miquels Thanks!
