### ISSUE TITLE
how to run the server

### ISSUE THREAD

**Issue by BarryGjl** [miquels/speedtest#5]
I can not run the server, please tell me the way，thanks！

**Comment by BarryGjl** [comment]
???

**Comment by elico** [comment]
@BarryGjl What OS and ARCH are you using?
I created an RPM package of the speedtest server and web service at:
- http://ngtech.co.il/repo/centos/7/SRPMS/speedtest-1.0.0-2.el7.centos.src.rpm
- http://ngtech.co.il/repo/centos/7/x86_64/speedtest-1.0.0-2.el7.centos.x86_64.rpm
- http://www1.ngtech.co.il/wpe/2017/12/24/squid-cache-4-0-22-rpms-released-speedtest-service-for-free/

I planned to packge it also for debian and ubuntu but yet to do so.
If you would give me\us more details I\us might be able to help you.

**Comment by teramix** [comment]
And for FreeBSD?

**Comment by elico** [comment]
@teramix I have my pre-compiled files at:
- http://gogs.ngtech.co.il/NgTech-LTD/html5-speedtest-servers
- http://gogs.ngtech.co.il/NgTech-LTD/html5-speedtest-servers/raw/master/speedtest-server/speedtest-server.tar.xz
- http://gogs.ngtech.co.il/NgTech-LTD/html5-speedtest-servers/raw/master/http-server-with-mw/http-server-with-mw.tar.xz
- http://gogs.ngtech.co.il/NgTech-LTD/html5-speedtest-servers/raw/master/speed-test-static-files.tar

**Comment by elico** [comment]
@teramix These static files will not be available privately for now.
I will try to publish them on the public space when I will have the resources for that.

**Comment by miquels** [comment]
Closing this issue because I'm archiving this repository.
