### ISSUE TITLE
error while installing with yarn MacOS

### ISSUE THREAD

**Issue by inglesuniversal** [miquels/speedtest#7]
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/xxxxx/Vue/speedtest/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.3.1/bin/node" "/Users/xxxxxxx/Vue/speedtest/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/xxxxxxx/Vue/speedtest/node_modules/node-sass
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this

Any idea how to fix that issue?

Thanks so much

**Comment by miquels** [comment]
It's may be because you were trying to use a way too modern `node` version with this project. I've updated all dependencies to the latest and greatest; it might work now. I'm not sure, I only develop / run this on linux... sorry.

**Comment by miquels** [comment]
Closing this issue because I'm archiving this repository.
